import * as pdfjsLib from 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs';

pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';

const config={apiKey:'AIzaSyCxPppnUG864v3E2j1OzykzFmhLpsEJCSE',authDomain:'chess-1885a.firebaseapp.com',projectId:'chess-1885a',appId:'1:824383572856:web:7c663d6bf0f970f6acd68d'};
const sources={
 'ch1-2-en':{title:'第 1～2 章｜英文版講義',src:'lectures/economics-ch1-2-en.pdf'},
 'ch3-4-en':{title:'第 3～4 章｜英文版講義',src:'lectures/economics-ch3-4-en.pdf'},
 'ch5-6-en':{title:'第 5～6 章｜英文版講義',src:'lectures/economics-ch5-6-en.pdf'},
 'ch7-8-en':{title:'第 7～8 章｜英文版講義',src:'lectures/economics-ch7-8-en.pdf'},
 'ch1-2-zh':{title:'第 1～2 章｜繁體中文翻譯版講義',src:'lectures/economics-ch1-2-zh.pdf',pending:true},
 'ch3-4-zh':{title:'第 3～4 章｜繁體中文翻譯版講義',src:'lectures/economics-ch3-4-zh.pdf',pending:true},
 'ch5-6-zh':{title:'第 5～6 章｜繁體中文翻譯版講義',src:'lectures/economics-ch5-6-zh.pdf',pending:true},
 'ch7-8-zh':{title:'第 7～8 章｜繁體中文翻譯版講義',src:'lectures/economics-ch7-8-zh.pdf',pending:true},
};
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search),shareId=params.get('share'),docId=params.get('doc')||'ch1-2-en',source=sources[docId];
const pdfCanvas=$('pdfCanvas'),ink=$('inkCanvas'),textLayer=$('textLayer'),shell=$('pageShell'),empty=$('emptyState'),lamp=$('syncLamp');
let auth=null,db=null,user=null,pdf=null,pageNo=1,scale=1.15,fitFirstMobilePage=true,tool='select',colour='#17324d',lineWidth=3,notes={pages:{}},pageHistory={},dirtyTimer=null,shared=false,activeTextId=null,dragText=null;
const guest=localStorage.getItem('econGuestMode')==='1';
const localKey=`econ848_lecture_notes_${docId}`;
const clone=v=>JSON.parse(JSON.stringify(v||{}));
const blank=()=>({strokes:[],texts:[]});
const now=()=>Date.now();
const pageKey=()=>String(pageNo);
const pageNotes=()=>notes.pages[pageKey()]||(notes.pages[pageKey()]=blank());
const hasContent=p=>Boolean(p&&(p.strokes?.length||p.texts?.some(t=>String(t.text||'').trim())));
const setLamp=(kind,message)=>{lamp.className='syncLamp '+kind;lamp.lastElementChild.textContent=message};
const showEmpty=message=>{empty.innerHTML=message;empty.classList.remove('hidden');shell.classList.add('hidden')};
const getLocal=()=>{try{return JSON.parse(localStorage.getItem(localKey)||'{"pages":{}}')}catch(_){return {pages:{}}}};
const setLocal=()=>localStorage.setItem(localKey,JSON.stringify(notes));
function ratio(v,max){return Math.max(0,Math.min(1,Number(v)||0))*max}
function normalized(event){const r=ink.getBoundingClientRect();return [Math.max(0,Math.min(1,(event.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(event.clientY-r.top)/r.height))]}
function paintStroke(ctx,stroke){const pts=stroke.points||[];if(!pts.length)return;ctx.save();ctx.lineCap='round';ctx.lineJoin='round';if(stroke.kind==='erase'){ctx.globalCompositeOperation='destination-out';ctx.lineWidth=(stroke.width||3)*3;ctx.globalAlpha=1}else{ctx.globalCompositeOperation='source-over';ctx.strokeStyle=stroke.color||'#17324d';ctx.lineWidth=stroke.width||3;ctx.globalAlpha=stroke.kind==='highlighter'?.3:1}ctx.beginPath();pts.forEach((p,i)=>{const x=ratio(p[0],ink.width),y=ratio(p[1],ink.height);if(i)ctx.lineTo(x,y);else ctx.moveTo(x,y)});if(pts.length===1)ctx.lineTo(ratio(pts[0][0],ink.width)+.1,ratio(pts[0][1],ink.height)+.1);ctx.stroke();ctx.restore()}
function renderInk(){const ctx=ink.getContext('2d');ctx.clearRect(0,0,ink.width,ink.height);for(const stroke of pageNotes().strokes||[])paintStroke(ctx,stroke)}
function textStyles(element,item){element.style.left=(item.x*100)+'%';element.style.top=(item.y*100)+'%';element.style.width=Math.max(70,item.w||130)+'px';element.style.height=Math.max(28,item.h||36)+'px';element.style.fontSize=(item.size||16)+'px';element.style.color=item.color||'#17324d';element.style.fontWeight=item.bold?'800':'400'}
function saveTextElement(el){const item=pageNotes().texts.find(x=>x.id===el.dataset.id);if(!item)return;item.text=el.innerText;item.w=Math.round(el.offsetWidth);item.h=Math.round(el.offsetHeight);pushHistory();queueSave()}
function renderText(){textLayer.innerHTML='';for(const item of pageNotes().texts||[]){const el=document.createElement('div');el.className='textBox';el.dataset.id=item.id;el.textContent=item.text||'';el.contentEditable='false';textStyles(el,item);el.addEventListener('dblclick',()=>{if(shared)return;el.contentEditable='true';el.focus();activeTextId=item.id});el.addEventListener('input',()=>{const target=pageNotes().texts.find(x=>x.id===item.id);if(target)target.text=el.innerText;queueSave()});el.addEventListener('blur',()=>{el.contentEditable='false';saveTextElement(el)});el.addEventListener('pointerdown',event=>startTextDrag(event,el));el.addEventListener('pointerup',()=>saveTextElement(el));el.addEventListener('keydown',event=>{if(event.key==='Escape'){el.blur()}if(event.key==='Delete'&&el.contentEditable==='false'){removeText(item.id)}});textLayer.append(el)}}
function renderNotes(){renderInk();renderText();updateHistoryButtons()}
function pushHistory(){const h=pageHistory[pageKey()]||(pageHistory[pageKey()]={undo:[],redo:[]});h.undo.push(JSON.stringify(pageNotes()));if(h.undo.length>35)h.undo.shift();h.redo=[];updateHistoryButtons()}
function restoreHistory(direction){const h=pageHistory[pageKey()]||(pageHistory[pageKey()]={undo:[],redo:[]}),from=direction==='undo'?h.undo:h.redo,to=direction==='undo'?h.redo:h.undo;if(!from.length)return;to.push(JSON.stringify(pageNotes()));notes.pages[pageKey()]=JSON.parse(from.pop());renderNotes();queueSave()}
function updateHistoryButtons(){const h=pageHistory[pageKey()]||{undo:[],redo:[]};$('undo').disabled=!h.undo.length||shared;$('redo').disabled=!h.redo.length||shared}
function queueSave(){if(shared)return;setLocal();setLamp(user?'pending':'local',user?'正在同步…':'本機已儲存');clearTimeout(dirtyTimer);dirtyTimer=setTimeout(saveCurrent,700)}
async function saveCurrent(){clearTimeout(dirtyTimer);setLocal();const contentPages=Object.entries(notes.pages).filter(([,p])=>hasContent(p));const meta={uid:user?.uid||null,lectureId:docId,openedAt:now(),updatedAt:now(),hasNotes:contentPages.length>0,noteCount:contentPages.length};try{if(user&&db){setLamp('pending','正在同步…');await db.collection('users').doc(user.uid).collection('lectureNotes').doc(docId).set(meta,{merge:true});await db.collection('users').doc(user.uid).collection('lectureNotes').doc(docId).collection('pages').doc(pageKey()).set({uid:user.uid,lectureId:docId,page:pageNo,data:pageNotes(),updatedAt:now()});setLamp('saved','雲端已同步')}else setLamp('local','本機已儲存')}catch(error){setLamp('failed','尚未同步／儲存失敗（本機保留）')}}
async function loadNotes(){notes=getLocal();if(!user||!db)return;try{setLamp('pending','載入雲端筆記…');const snap=await db.collection('users').doc(user.uid).collection('lectureNotes').doc(docId).collection('pages').get();snap.forEach(row=>{const d=row.data();if(d?.page&&d.data)notes.pages[String(d.page)]=d.data});setLocal();setLamp('saved','雲端已同步')}catch(error){setLamp('failed','雲端筆記載入失敗，使用本機版本')}}
function startTextDrag(event,el){if(shared||tool!=='select'||el.contentEditable==='true')return;event.preventDefault();const item=pageNotes().texts.find(x=>x.id===el.dataset.id);if(!item)return;pushHistory();dragText={el,item,startX:event.clientX,startY:event.clientY,x:item.x,y:item.y};el.setPointerCapture?.(event.pointerId)}
function moveText(event){if(!dragText)return;const r=shell.getBoundingClientRect();dragText.item.x=Math.max(0,Math.min(.96,dragText.x+(event.clientX-dragText.startX)/r.width));dragText.item.y=Math.max(0,Math.min(.96,dragText.y+(event.clientY-dragText.startY)/r.height));textStyles(dragText.el,dragText.item)}
function stopText(){if(!dragText)return;dragText=null;queueSave()}
function addText(event){if(shared)return;const r=shell.getBoundingClientRect();pushHistory();const item={id:'t-'+now()+'-'+Math.random().toString(36).slice(2,7),x:(event.clientX-r.left)/r.width,y:(event.clientY-r.top)/r.height,w:150,h:38,size:Number($('textSize').value)||16,color:colour,bold:$('bold').classList.contains('active'),text:'輸入文字'};pageNotes().texts.push(item);renderText();const el=textLayer.querySelector(`[data-id="${item.id}"]`);el.contentEditable='true';el.focus();activeTextId=item.id;queueSave()}
function removeText(id){if(shared)return;pushHistory();pageNotes().texts=pageNotes().texts.filter(x=>x.id!==id);renderText();queueSave()}
function setTool(next){tool=next;document.querySelectorAll('[data-tool]').forEach(button=>button.classList.toggle('active',button.dataset.tool===next));shell.classList.toggle('selecting',next==='select');shell.classList.toggle('textMode',next==='text');ink.style.pointerEvents=next==='select'?'none':'auto'}
async function renderPage(next=pageNo){if(!pdf)return;pageNo=Math.max(1,Math.min(pdf.numPages,Number(next)||1));$('pageInput').value=pageNo;$('pageReadout').textContent=`第 ${pageNo} / ${pdf.numPages} 頁`;const page=await pdf.getPage(pageNo);if(fitFirstMobilePage&&innerWidth<700){const nativeWidth=page.getViewport({scale:1}).width,available=document.querySelector('.readerMain').clientWidth-12;scale=Math.max(.42,Math.min(1.15,available/nativeWidth));fitFirstMobilePage=false}$('zoomReadout').textContent=Math.round(scale*100)+'%';const view=page.getViewport({scale});pdfCanvas.width=Math.ceil(view.width);pdfCanvas.height=Math.ceil(view.height);ink.width=pdfCanvas.width;ink.height=pdfCanvas.height;shell.style.width=pdfCanvas.width+'px';shell.style.height=pdfCanvas.height+'px';await page.render({canvasContext:pdfCanvas.getContext('2d'),viewport:view}).promise;renderNotes()}
async function openPdf(){if(!source){showEmpty('找不到指定的講義。請回到講義專區重新選擇。');return}document.title=source.title;$('docTitle').textContent=source.title;if(source.pending){showEmpty('<h2>中文版講義準備中</h2><p>此教材卡與獨立筆記空間已建立；完整的繁體中文版 PDF 仍在進行逐頁翻譯與版面校對，尚未發布，以免以未完整內容取代原講義。</p>');return}try{pdf=await pdfjsLib.getDocument(source.src).promise;empty.classList.add('hidden');shell.classList.remove('hidden');await renderPage(1)}catch(error){showEmpty('<h2>無法開啟講義 PDF</h2><p>請確認網路連線後重試。</p>')}}
async function searchText(term){const query=String(term||'').trim().toLowerCase();if(!query||!pdf)return;setLamp('pending','正在搜尋講義…');for(let n=1;n<=pdf.numPages;n++){const content=await (await pdf.getPage(n)).getTextContent();const text=content.items.map(x=>x.str).join(' ').toLowerCase();if(text.includes(query)){await renderPage(n);$('searchResult').textContent=`找到第 ${n} 頁`;setLamp(user?'saved':'local',user?'雲端已同步':'本機已儲存');return}}$('searchResult').textContent='找不到結果';setLamp(user?'saved':'local',user?'雲端已同步':'本機已儲存')}
function exportImage(){const out=document.createElement('canvas'),ctx=out.getContext('2d');out.width=pdfCanvas.width;out.height=pdfCanvas.height;ctx.drawImage(pdfCanvas,0,0);ctx.drawImage(ink,0,0);for(const text of pageNotes().texts||[]){ctx.save();ctx.fillStyle=text.color||'#17324d';ctx.font=`${text.bold?'800':'400'} ${text.size||16}px system-ui`;ctx.textBaseline='top';ctx.fillText(text.text||'',ratio(text.x,out.width),ratio(text.y,out.height),text.w||150);ctx.restore()}const a=document.createElement('a');a.download=`${docId}-page-${pageNo}-notes.png`;a.href=out.toDataURL('image/png');a.click()}
async function exportPdf(){const {jsPDF}=await import('https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.2/jspdf.es.min.js');const out=document.createElement('canvas'),ctx=out.getContext('2d');out.width=pdfCanvas.width;out.height=pdfCanvas.height;ctx.drawImage(pdfCanvas,0,0);ctx.drawImage(ink,0,0);for(const text of pageNotes().texts||[]){ctx.fillStyle=text.color||'#17324d';ctx.font=`${text.bold?'800':'400'} ${text.size||16}px system-ui`;ctx.textBaseline='top';ctx.fillText(text.text||'',ratio(text.x,out.width),ratio(text.y,out.height),text.w||150)}const orientation=out.width>out.height?'landscape':'portrait',doc=new jsPDF({orientation,unit:'px',format:[out.width,out.height]});doc.addImage(out.toDataURL('image/jpeg',.92),'JPEG',0,0,out.width,out.height);doc.save(`${docId}-page-${pageNo}-notes.pdf`)}
function randomToken(){const bytes=new Uint8Array(18);crypto.getRandomValues(bytes);return [...bytes].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function share(){if(!user||!db){alert('分享個人筆記需要先登入帳號；訪客筆記不會上傳或公開。');return}try{await saveCurrent();setLamp('pending','正在建立分享連結…');const snap=await db.collection('users').doc(user.uid).collection('lectureNotes').doc(docId).collection('pages').get();const pages={};snap.forEach(row=>pages[row.id]=row.data().data);const token=randomToken();await db.collection('sharedLectureNotes').doc(token).set({ownerUid:user.uid,lectureId:docId,pages,createdAt:now(),updatedAt:now()});const url=new URL(location.href);url.search='share='+token;$('shareUrl').value=url.href;$('shareDialog').showModal();setLamp('saved','雲端已同步')}catch(error){setLamp('failed','建立分享連結失敗')}}
async function loadShare(){try{const row=await db.collection('sharedLectureNotes').doc(shareId).get();if(!row.exists)throw Error('missing');const data=row.data();if(!sources[data.lectureId])throw Error('source');shared=true;notes={pages:data.pages||{}};document.body.classList.add('shared');$('docTitle').textContent=(sources[data.lectureId].title||'講義')+'｜分享檢視';document.querySelector('.readerTools').classList.add('hidden');$('saveBtn').classList.add('hidden');$('shareBtn').classList.add('hidden');setLamp('saved','分享檢視：唯讀');await openPdf()}catch(error){showEmpty('<h2>這個分享連結無法使用</h2><p>可能已失效或不存在。</p>')}}
function bind(){document.querySelectorAll('[data-tool]').forEach(button=>button.onclick=()=>setTool(button.dataset.tool));$('color').oninput=e=>{colour=e.target.value;const item=pageNotes().texts.find(x=>x.id===activeTextId);if(item){item.color=colour;renderText();queueSave()}};$('width').oninput=e=>lineWidth=Number(e.target.value);$('bold').onclick=()=>{const b=$('bold');b.classList.toggle('active');const item=pageNotes().texts.find(x=>x.id===activeTextId);if(item){item.bold=b.classList.contains('active');renderText();queueSave()}};$('textSize').oninput=e=>{const item=pageNotes().texts.find(x=>x.id===activeTextId);if(item){item.size=Number(e.target.value);renderText();queueSave()}};$('prev').onclick=()=>renderPage(pageNo-1);$('next').onclick=()=>renderPage(pageNo+1);$('pageInput').onchange=e=>renderPage(e.target.value);$('zoomIn').onclick=()=>{scale=Math.min(2.4,scale+.15);renderPage()};$('zoomOut').onclick=()=>{scale=Math.max(.55,scale-.15);renderPage()};$('undo').onclick=()=>restoreHistory('undo');$('redo').onclick=()=>restoreHistory('redo');$('saveBtn').onclick=saveCurrent;$('clearPage').onclick=()=>{if(confirm('確定要清除目前頁面全部筆記嗎？此操作無法復原。')){pushHistory();notes.pages[pageKey()]=blank();renderNotes();queueSave()}};$('clearAll').onclick=async()=>{if(!confirm('確定要清除整份講義的所有筆記嗎？此操作無法復原。'))return;notes={pages:{}};setLocal();if(user&&db){try{const ref=db.collection('users').doc(user.uid).collection('lectureNotes').doc(docId),pages=await ref.collection('pages').get(),batch=db.batch();pages.forEach(row=>batch.delete(row.ref));batch.delete(ref);await batch.commit();setLamp('saved','雲端筆記已清除')}catch(e){setLamp('failed','雲端清除失敗；請稍後重試')}}renderNotes()};$('exportImage').onclick=exportImage;$('exportPdf').onclick=exportPdf;$('shareBtn').onclick=share;$('copyShare').onclick=async()=>{await navigator.clipboard.writeText($('shareUrl').value);$('copyShare').textContent='已複製'};$('searchForm').onsubmit=e=>{e.preventDefault();searchText($('searchInput').value)};ink.addEventListener('pointerdown',event=>{if(shared)return;if(tool==='text'){addText(event);return}if(!['pen','highlighter','eraser'].includes(tool))return;pushHistory();const stroke={kind:tool==='eraser'?'erase':tool,color:colour,width:lineWidth,points:[normalized(event)]};pageNotes().strokes.push(stroke);ink.setPointerCapture(event.pointerId);renderInk()});ink.addEventListener('pointermove',event=>{if(!ink.hasPointerCapture(event.pointerId))return;const strokes=pageNotes().strokes;if(!strokes.length)return;strokes[strokes.length-1].points.push(normalized(event));renderInk()});ink.addEventListener('pointerup',event=>{if(ink.hasPointerCapture(event.pointerId)){ink.releasePointerCapture(event.pointerId);queueSave()}});document.addEventListener('pointermove',moveText);document.addEventListener('pointerup',stopText);window.addEventListener('beforeunload',()=>{if(!shared){setLocal();saveCurrent()}});setTool('select')}
async function boot(){bind();if(!source){showEmpty('找不到講義。');return}try{firebase.initializeApp(config);auth=firebase.auth();db=firebase.firestore();auth.onAuthStateChanged(async u=>{user=u||null;if(shareId){await loadShare();return}if(!user&&!guest){location.replace('index.html');return}await loadNotes();await openPdf();if(!user)setLamp('local','本機已儲存')})}catch(error){if(shareId){showEmpty('此分享連結需要 Firebase 連線才能開啟。');return}if(!guest){location.replace('index.html');return}notes=getLocal();setLamp('local','訪客模式：本機已儲存');openPdf()}}
boot();
